version: "3.3"
services:
  kibana:
    image: "bitnami/kibana:latest"
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    volumes:
      - "kibana_data:/bitnami"
  elasticsearch:
    image: "bitnami/elasticsearch:latest"
    ports:
      - 9200:9200
    volumes:
      - "elasticsearch_data:/bitnami"
volumes:
  kibana_data:
    driver: local
  elasticsearch_data:
    driver: local
